#!/bin/bash

for i in `seq 1 10000`;
do

export temp=$(echo $RANDOM % 100 + 1| bc)
export hum=$(echo $RANDOM % 100 + 1 | bc)

export load_IR=$(echo $RANDOM % 100 + 1 | bc)
export load_IC=$(echo $RANDOM % 100 + 1 | bc)

export state_UV=0
export state_HUM=1


#export payload="{\"enclosureNodeID\":\"1\",\"temperature\":\"$temp\",\"humidity\":\"$hum\",\"Load_IR\":\"$load_IR\",\"Load_IC\":\"$load_IC\",\"State_UV\":\"$state_UV\",\"State_HUM\":\"$state_HUM\"}"
export payload="{\"CLIENTID\":\"1\",\"TEMP\":\"$temp\",\"RH\":\"$hum\",\"IR_PW\":\"$load_IR\",\"IC_PW\":\"$load_IC\",\"UV_STATUS\":\"1\",\"HUMI_STATUS\":\"0\"}"

echo $payload

#curl -H "Content-Type: application/json" -d $payload -X POST http://localhost/api/telemetry 


         #curl -H "Content-Type: application/json" -d $payload -X POST http://192.168.0.253/api/telemetry 
         mosquitto_pub -h localhost -t local -m $payload
         echo
         sleep 0.100
done  
